[package]
name = "redis_pool"
version = "0.1.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a redis client and cluster client pools."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_odbc"
keywords = ["Redis", "Pool", "tokio"]
repository = "https://github.com/AscendingCreations/RedisPool"

[features]
json  = ["redis/json"]
axum = ["axum-core", "http"]
cluster = ["redis/cluster-async"]

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
async-trait = "0.1.71"
tracing = "0.1.37"
thiserror = "1.0.43"
redis = { version = "0.23.3", features = ["aio", "tokio-comp", "keep-alive", "cluster-async"]}
once_cell = "1.18.0"
crossbeam-queue = "0.3.8"
axum-core = {version = "0.3.4", optional = true}
http = {version = "0.2.9", optional = true}